version: '2'

services:
  web:
    image: nginx:latest
    volumes:
      - ./vulnerable.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  secret:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
    expose:
      - "80"
